# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-27 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeployInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repoName', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=10)),
                ('revision', models.CharField(max_length=100)),
                ('person', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('log', models.TextField()),
            ],
            options={
                'db_table': 'ops_deploy_info',
            },
        ),
        migrations.CreateModel(
            name='RepoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repoName', models.CharField(max_length=100)),
                ('repoAddress', models.CharField(max_length=100)),
                ('repoUser', models.CharField(max_length=50)),
                ('repoPassword', models.CharField(blank=True, max_length=50)),
                ('wwwDir', models.CharField(max_length=50)),
                ('testDeployIP', models.CharField(max_length=50)),
                ('preDeployIP', models.CharField(max_length=50)),
                ('onlineDeployIP', models.CharField(max_length=500)),
                ('localCheckoutDir', models.CharField(max_length=100)),
                ('excludeDir', models.CharField(max_length=500)),
                ('repoType', models.CharField(choices=[('svn', 'svn repo type'), ('git', 'git repo type')], max_length=5)),
                ('addDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'ops_repo_info',
            },
        ),
    ]
