# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repoName', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=10)),
                ('revision', models.CharField(max_length=100)),
                ('person', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('log', models.TextField()),
            ],
            options={
                'db_table': 'ops_deploy_info',
            },
        ),
    ]
