# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-30 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollBackInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repoName', models.CharField(max_length=100)),
                ('curRevision', models.CharField(max_length=30)),
                ('backRevision', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('success', 'rollback success'), ('failed', 'rollback failed')], max_length=10)),
                ('rollDate', models.DateTimeField()),
                ('target', models.CharField(max_length=10)),
                ('person', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'ops_rollback_info',
            },
        ),
    ]
