# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-02 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0002_rollbackinfomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployinfomodel',
            name='remark',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
