# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0003_deployinfomodel_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployinfomodel',
            name='remark',
            field=models.CharField(default=None, max_length=80),
        ),
    ]
