# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-27 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmdLogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('command', models.CharField(max_length=2000)),
                ('login_ip', models.CharField(max_length=20)),
                ('runtime', models.DateTimeField()),
            ],
            options={
                'db_table': 'ops_cmd_opt_log',
            },
        ),
    ]
