# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-05 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeRepoAuthInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('reponame', models.CharField(max_length=50)),
                ('accessauth', models.CharField(max_length=100)),
                ('envtype', models.CharField(max_length=20)),
                ('createtime', models.DateTimeField()),
                ('comment', models.CharField(max_length=200)),
                ('repotype', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseAuthInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('accesshost', models.CharField(max_length=100)),
                ('accessdb', models.CharField(max_length=100)),
                ('accessauth', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=20)),
                ('useperson', models.CharField(max_length=100)),
                ('envtype', models.CharField(max_length=20)),
                ('createtime', models.DateTimeField()),
                ('comment', models.CharField(max_length=1000)),
            ],
        ),
    ]
