# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-05 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coderepoauthinfomodel',
            table='ops_repo_auth_info',
        ),
        migrations.AlterModelTable(
            name='databaseauthinfomodel',
            table='ops_db_auth_info',
        ),
    ]
