# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('ipaddress', models.CharField(max_length=200)),
                ('cpuinfo', models.CharField(max_length=50)),
                ('meminfo', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=50)),
                ('osinfo', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=100)),
                ('usage', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'ops_host_info',
            },
        ),
    ]
