# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDeployLogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('target', models.CharField(max_length=100)),
                ('application', models.CharField(max_length=100)),
                ('mapping', models.CharField(max_length=20)),
                ('log', models.TextField()),
            ],
            options={
                'db_table': 'ops_app_deploy_log',
            },
        ),
    ]
