# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdeploylogmodel',
            name='duration',
            field=models.CharField(max_length=500),
        ),
    ]
