# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-18 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salts', '0002_auto_20170413_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinedeploymodel',
            name='deploy_status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
